### write a program in python that reads data values as product name and price .For this it asks user to enter such data pairs until user says no .store the data in a dictionary whose keys are the product name and the data name  and whose values are the prices. when the user is done entering products and prices allow them to enter a product name and print the corresponding price or a message if the product is not in the data .Also , allows the user to enter price range and print out all the products whose price is within that range. take at least 8 such data

In [ ]:
products = {}

# Input loop to enter product names and prices
while True:
    product_name = input("Enter product name: ")
    price = float(input("Enter price: "))
    products[product_name] = price

    cont = input("Do you want to enter another product? (yes/no): ")
    if cont.lower() != "yes":
        break

# Search for a product by name
search_product = input("Enter a product name to get its price: ")
if search_product in products:
    print(f"The price of {search_product} is: {products[search_product]}")
else:
    print("Product not found.")

# Search for products within a price range
min_price = float(input("Enter minimum price: "))
max_price = float(input("Enter maximum price: "))

matching_products = [product for product, price in products.items() if min_price <= price <= max_price]

if matching_products:
    print("Products within the price range:")
    for product in matching_products:
        print(f"{product}: {products[product]}")
else:
    print("No products found within the price range.")

#2.	Here is an example dictionary. You may insert more data of choice.
### d=[(‘name“.‘Ram’, ‘phone“.‘9434141414’, ‘email".‘ram@gmail.com’}, (‘name".‘Laksman’,‘phone".‘8434151515’,”}, (‘name’:‘Bharat’,‘phone’:‘7474161616’, ‘email’:‘bharat@mnai1.com’}, (‘name’:‘Satrughna’,‘phone“.‘9478171717’, ‘email’:‘satrughna@gmail.com’}]
Write a program in Python that reads the above dictionary and prints the following:
(a)	All the users whose phone number ends in 5
(b)	All the users that don’t have an email address listed
(c)	All the users whose phone number starts with 9

In [ ]:
d = [
    {'name': 'Ram', 'phone': '9434141414', 'email': 'ram@gmail.com'},
    {'name': 'Laksman', 'phone': '8434151515'},
    {'name': 'Bharat', 'phone': '7474161616', 'email': 'bharat@mnai1.com'},
    {'name': 'Satrughna', 'phone': '9478171717', 'email': 'satrughna@gmail.com'}
]

# (a) All users whose phone number ends in 5
print("Users whose phone number ends in 5:")
for user in d:
    if user.get('phone', '').endswith('5'):
        print(user['name'])

# (b) All users that don’t have an email address listed
print("\nUsers without an email address:")
for user in d:
    if 'email' not in user:
        print(user['name'])

# (c) All users whose phone number starts with 9
print("\nUsers whose phone number starts with 9:")
for user in d:
    if user.get('phone', '').startswith('9'):
        print(user['name'])

### 3.	Write a class in Python called PyConverter. User will pass a length and a unit when declaring an object from the class, for example ob = PyConverter (9, ‘meters’). Consider units to be kilometers, meters and centimeters. For each of these units there should be a method that returns the length output converted into those imits. For example, using the PyConverter object if the user calls ob.centimeter(), he should get 900 as the result.

In [ ]:
class PyConverter:
    def __init__(self, length, unit):
        self.length = length
        self.unit = unit.lower()

    def kilometer(self):
        if self.unit == 'kilometers':
            return self.length
        elif self.unit == 'meters':
            return self.length / 1000
        elif self.unit == 'centimeters':
            return self.length / 100
        else:
            print("Invalid unit provided.")

    def meter(self):
        if self.unit == 'meters':
            return self.length
        elif self.unit == 'kilometers':
            return self.length * 1000
        elif self.unit == 'centimeters':
            return self.length / 100
        else:
            print("Invalid unit provided.")

    def centimeter(self):
        if self.unit == 'centimeters':
            return self.length
        elif self.unit == 'kilometers':
            return self.length * 100000
        elif self.unit == 'meters':
            return self.length * 100
        else:
            print("Invalid unit provided.")

# Example usage:
ob = PyConverter(9, 'meters')
print("Length in centimeters:", ob.centimeter())  # Output: 900

Invalid unit provided.
Length in centimeters: None

# Write a python program to input sets S1 and S2 containing names of cities. Then perform the following:
(a) Find union ,intersection and symmetric difference of the two sets.
(b) Display elements of S1 in upper case and display S2 in lower case.

In [ ]:
S1 = set(input("Enter the cities name"))
S2 = set(input("Enter the cities name"))

union_set = S1.union(S2)
intersection_set = S1.intersection(S2)
symmetric_difference_set = S1.symmetric_difference(S2)

print("Union of S1 and S2:", union_set)
print("Intersection of S1 and S2:", intersection_set)
print("Symmetric Difference of S1 and S2:", symmetric_difference_set)

print("Elements of S1 in upper case:", {city.upper() for city in S1})
print("Elements of S2 in lower case:", {city.lower() for city in S2})

# write a program in python to find all numbers between 1 and N those are divisible  by  7 and ends with 6 also display there count

In [ ]:
N= int(input("Enter the range"))
i = 1
count = 0
for i in range(1, N + 1):
  if(i % 7 == 0 and i % 10 == 6):
    count+=1
    print ("list of number",[i])
    print ("count = ",count)

# write a program in python to input different names in any case Now convert the upper case into lower case letters and lower case letters to upper case letters

In [ ]:
name = input("Enter the name ")
converted_name=""
for char in name:
  if char.isupper():
    converted_name += char.lower()
  elif char.islower():
    converted_name += char.upper()
  else:
    converted_name += char
print (converted_name)

Enter the name Somsubhro
sOMSUBHRO

# Check a given string is Heterogram or not

In [ ]:
string = input("Enter the string : ")
string_without_punctuation = "".join(char for char in string if char.isalnum())
string_without_spaces = string_without_punctuation.replace(" ", "")
character = set(string_without_spaces)
if(len(string_without_spaces) == len(character)):
  print("Yes")
else:
  print("No")

Enter the string : the big-drawf  only_jumps
Yes

# A string is pangram or not

In [ ]:
import string
string = input("Enter the string: ")
string_lower = string.lower()
flag =0
all_Alphabets = "abcdefghijklmnopqrstuvwxyz"
for char in all_Alphabets:
  if char in string_lower:
    flag = 1
  else:
    flag = 0
if(flag == 1):
  print("pangram")
else:
  print("pangram not")

Enter the string: pack my box with five dozen liquor jugs
pangram

# Count even and odd number in a list

In [ ]:
list = [10,11,12,13,14,15]
even = 0
odd = 0
for i in list:
  if(i%2 == 0):
    even +=1
  else:
    odd +=1
print("Odd number : ",odd)
print("Even number : ",even)

Odd number :  3
Even number :  3

GCD and LCM of two number

In [ ]:
def gcd(a,b):
    while b!=0:
        temp=a%b
        a=b
        b=temp
    return a
def lcm(a,b):
    max=a if a>=b else b
    while max%a!=0 or max%b!=0:
        max+=1
    return max
def lcm_alt(a,b):
    return (a*b)//gcd(a,b)

def gcdR(a,b):
    if b==0:
        return a
    else:
        return gcd(b,a%b)

def lcmR(a,b):
    if a%b==0:
        return a
    else:
        temp=a%b
        return a*lcm(b,a%b)//temp
print(gcd(8,12))
print(gcdR(8,12))
print(lcm(8,12))
print(lcm_alt(8,12))
print(lcmR(8,12))

4
4
24
24
24

write a python program that accepts a hyphen_separated sequence after sorting them alphabetically.
Sample Items : green-red-yellow-balck-white
Expected Items
black-green-red-white-yellow

In [ ]:
sequence = "green-red-yellow-black-white"
items = sequence.split("-")
sorted_items = sorted(items)
sorted_sequence = '-'.join(sorted_items)
print(sorted_sequence)

#Find power of number using recursion

In [ ]:
N=int(input("Enter the base number : "))
P=int(input("Enter the power number : "))
result = 1
if P==0:
  result=1
  print(result)
else:
  for _ in range(P):
    result *= N
  print(result)

Enter the base number : 3
Enter the power number : 4
81

Write a program to create a function "show employee" using the following condition:
it should accept both name and salary and display both

In [ ]:
def show_employee(name, salary):
  print(f"Employee Name: {name}")
  print(f"Employee Salary: ${salary:.2f}")

# Example usage
employee_name = "John Doe"
employee_salary = 50000.00

show_employee(employee_name, employee_salary)

Employee Name: John Doe
Employee Salary: $50000.00

Calculate hermonic sum to n-1

In [ ]:
n = int(input("Enter the number : "))
sum = 1
for i in range(1,n-1):
  sum = sum + (1/i)
print (sum)

#Exception

In [ ]:
# NameError
try:
    #age=18
    print('Age:',age)       #This will cause the exception
except NameError as ne:
    print('NameError:',ne)

# ValueError
try:
    num=int('50')
    #num=int('abc')         #This will cause the exception
except ValueError as ve:
    print('ValueError:',ve)
else:
    print(num)

# ZeroDivisionError
try:
    a=5
    b=3
    c=(a+b)/(b-3)
except ZeroDivisionError as zde:
    print('ZeroDivisionError:',zde)
else:
    print(c)

# Index Error
try:
    lst=[1,2,3,4,5]
    string='The Batman'
    item=lst[10]
    char=string[10]
except IndexError as ie:
    print('IndexError:',ie)
else:
    print(item,char)

# SyntaxError
try:
    date=eval(input('Enter a date:'))
except SyntaxError as se:
    print(se)
else:
    print(date)

# IOError
try:
    f=open('barca.txt','r')
except IOError as ioe:
    print('IOError:',ioe)

# TypeError
def avg(lst):
    t=0
    for n in lst:
        t+=n
    return t/len(lst)
try:
    lst=[1,2,3,4,'a']
    a=avg(lst)
except TypeError as te:
    print('TypeError:',te)
except ZeroDivisionError as zde:
    print('ZeroDivisionError:',zde)
else:
    print(a)

Write a program in Python that populates an empty list with integers, each which are either 0 or 1. Then
find the size of the longest chain of zeros. Also give the span of indices containing the longest chain.
the longest run of zeros in [1,0,1,0,0,0,1,0,0,0,0,0,0,1,0,0,0,0,1] is 6.

In [ ]:
data = [1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1]

# Initialize variables
current_count = 0
max_count = 0
start_index = 0

for i in range(len(data)):
    value = data[i]
    if value == 0:
        current_count += 1
    else:
        # Update max_count and start_index if necessary
        if current_count > max_count:
            max_count = current_count
            start_index = i - max_count
        current_count = 0

# Check for the last chain of zeros
if current_count > max_count:
    max_count = current_count
    start_index = i - max_count + 1

# Print the results
print(f"Longest run of zeros: {max_count}")
print(f"Span of indices: [{start_index}, {start_index + max_count - 1}]")

Armstrong number

In [ ]:
def armstrong(number):
  num = str(number)
  power = len(num)
  total = sum(int(digit)**power for digit in num)
  return total == number
number = int(input("Enter the number:"))
if armstrong(number):
  print("Armstrong")
else:
  print("Not Armstrong")